apiVersion: v1
kind: Service
metadata:
  name: lab-app-service
  namespace: production
spec:
  type: NodePort
  selector:
    app: lab-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30082
